### ISSUE TITLE
URL Summary

### ISSUE THREAD

**Issue by JoshuaBThomas** [MattRuddick/intileryExtension#1]
A summary at the top with itqs coming through and the URL you were/are on would be very helpful.

**Comment by MattRuddick** [comment]
@JoshuaBThomas we now have URL changes appear in the c.gif logs (see screenshot).  This enhancement will be included in the next release and will be available to use very shortly.

![URL Changes Logged](https://user-images.githubusercontent.com/18257886/28061816-b4840ebe-6623-11e7-98de-7eec6efa67aa.png)
